query hello {
  hello
}

mutation login($account: String, $password: String) {
  login(account: $account, password: $password) {
    token
    userId
  }
}

mutation setHello($hello: String) {
  setHello(hello: $hello)
}

subscription helloWs($key: String) {
  helloWs(key: $key)
}
