query hello {
  hello
}

mutation loginByEmail($email: String!, $password: String!) {
  loginByEmail(email: $email, password: $password) {
    userId
    token
  }
}

mutation sayHello($hello: String) {
  sayHello(hello: $hello)
}

subscription helloWs {
  helloWs
}
