scalar Void

scalar Date

interface System {
  createTime: Date!
  updateTime: Date!
}

input IdInput {
  id: String!
}

type Image {
  name: String!
  url: String!
}

type Query {
  hello: String!
}

type Mutation {
  sayHello(hello: String): Boolean!
}

type Subscription {
  helloWs(key: String): String!
}
