scalar Void

scalar Date

type AuthInfo {
  token: String!
  userId: String!
}

type Query {
  hello: String!
}

type Mutation {
  setHello(hello: String): Boolean!
  login(account: String, password: String): AuthInfo!
}

type Subscription {
  helloWs(key: String): String!
}
